###############################
#  Taps                       #
###############################
# tap "homebrew/bundle"
# tap "homebrew/cask-versions"
# tap "homebrew/services"
# tap "homebrew/cask"
###############################
#  brew                       #
###############################
brew "python@3.9"
###############################
#  Cask                       #
###############################
cask "google-chrome"
cask "slack"
cask "docker"
cask "obsidian"
cask "visual-studio-code"
cask "postman"